#!/usr/bin/env python3
"""Emit the SPA's entity-id maps from brain/dsc_brain/entity_tables.py.

Roughly 660 HA-shaped entity ids used to be hand-synced across two languages.
This script makes the Python tables the single source of truth and writes the
TypeScript mirrors, so a rename on either side fails the build instead of
failing silently on the Pi.

    python brain/scripts/gen_entity_maps.py            # write
    python brain/scripts/gen_entity_maps.py --check    # diff, exit 1 on drift

``--check`` is also asserted by brain/tests/test_entity_maps_generated.py, and
exposed to the frontend as ``npm run gen:entities`` / ``gen:entities:check``.

This is a pure codegen tool: it never touches a device, a host or the network.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any

_HERE = Path(__file__).resolve()
BRAIN_DIR = _HERE.parent.parent
REPO_ROOT = BRAIN_DIR.parent

if str(BRAIN_DIR) not in sys.path:
    sys.path.insert(0, str(BRAIN_DIR))

from dsc_brain import entity_tables as T  # noqa: E402

GEN_DIR = REPO_ROOT / "frontend" / "src" / "lib" / "generated"

# Where the header points people who try to edit the output.
_SOURCE = "brain/dsc_brain/entity_tables.py"
_GENERATOR = "brain/scripts/gen_entity_maps.py"

# snake_case (Python table) → camelCase (TypeScript surface).
_KEY_ALIASES: dict[str, str] = {
    "seat_id": "seatId",
    "in_service_entity": "inServiceEntity",
    "planned_when_off": "plannedWhenOff",
    "demand_entity": "demandEntity",
    "relay_entity": "relayEntity",
    "link_entity": "linkEntity",
    "runtime_today": "runtimeToday",
    "cycles_today": "cyclesToday",
    "firmware_entity": "firmwareEntity",
}


def _header(what: str) -> str:
    return (
        f"// DO NOT EDIT — generated by {_GENERATOR} from {_SOURCE}.\n"
        f"// {what}\n"
        f"// Regenerate: `npm run gen:entities` (in frontend/) or\n"
        f"// `python {_GENERATOR}`.  `npm run gen:entities:check` (and the pytest\n"
        f"// brain/tests/test_entity_maps_generated.py) fail when this file drifts\n"
        f"// from the Python tables — a one-sided entity rename breaks the build,\n"
        f"// not the grow."
    )


def _ts_key(key: str) -> str:
    """A bare identifier where TS allows it, a quoted string otherwise."""
    if key and (key[0].isalpha() or key[0] == "_") and all(c.isalnum() or c == "_" for c in key):
        return key
    return json.dumps(key)


def _ts_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, (int, float)):
        return json.dumps(value)
    raise TypeError(f"unsupported entity-table value: {value!r}")


def _ts_inline_object(row: dict[str, Any]) -> str:
    parts = [f"{_ts_key(_KEY_ALIASES.get(k, k))}: {_ts_value(v)}" for k, v in row.items()]
    return "{ " + ", ".join(parts) + " }"


def _ts_block_object(row: dict[str, Any], indent: str) -> str:
    lines = [f"{indent}  {_ts_key(_KEY_ALIASES.get(k, k))}: {_ts_value(v)}," for k, v in row.items()]
    return "{\n" + "\n".join(lines) + f"\n{indent}}}"


def _string_record(name: str, table: dict[str, str]) -> str:
    lines = [f"export const {name}: Record<string, string> = {{"]
    for key, value in table.items():
        lines.append(f"  {_ts_key(key)}: {_ts_value(value)},")
    lines.append("};")
    return "\n".join(lines)


def render_entity_fleet_map() -> str:
    out = [
        _header("HA entity_id → fleet seat metric (Pi history + held readings)."),
        "",
        'import type { EntityFleetRef } from "../entityFleetMap";',
        "",
        "export const ENTITY_FLEET_MAP: Record<string, EntityFleetRef> = {",
    ]
    for entity_id, ref in T.ENTITY_FLEET_MAP.items():
        for comment in T.ENTITY_FLEET_MAP_COMMENTS.get(entity_id, ()):
            out.append(f"  // {comment}")
        out.append(f"  {json.dumps(entity_id)}: {_ts_inline_object(ref)},")
    out.append("};")
    out.append("")
    return "\n".join(out)


def render_fleet_entities() -> str:
    out = [
        _header("Seat → entity contracts for the hass-shaped compatibility shim."),
        "",
        _string_record("IN_SERVICE_ENTITIES", T.IN_SERVICE_ENTITIES),
        "",
        _string_record("SONOFF_FW", T.SONOFF_FW),
        "",
        _string_record("SONOFF_RELAY", T.SONOFF_RELAY),
        "",
    ]
    return "\n".join(out)


def render_kit_defs() -> str:
    out = [
        _header("Kit page node definitions (Kit Pulse / Fleet)."),
        "",
        'import type { KitDef } from "../kitInventory";',
        "",
        "export const KIT_DEFS: KitDef[] = [",
    ]
    for row in T.KIT_DEFS:
        out.append(f"  {_ts_block_object(row, '  ')},")
    out.append("];")
    out.append("")
    return "\n".join(out)


def render_kit_probes() -> str:
    def tuple_literal(name: str, doc: str, values: tuple[int, ...]) -> str:
        body = ", ".join(str(v) for v in values)
        return f"/** {doc} */\nexport const {name} = [{body}] as const;"

    out = [
        _header("Probe number sets shared by the kit maps and the SPA."),
        "",
        tuple_literal(
            "ALL_PROBE_NUMBERS",
            "Full entity universe (Device restore / maps). Not the Live kit.",
            T.ALL_PROBE_NUMBERS,
        ),
        "",
        tuple_literal(
            "KIT_PROBE_NUMBERS",
            "Operator kit — Live Root, honesty, Fleet pulse, idle-home defaults.",
            T.KIT_PROBE_NUMBERS,
        ),
        "",
    ]
    return "\n".join(out)


TARGETS: dict[str, Any] = {
    "entityFleetMap.gen.ts": render_entity_fleet_map,
    "kitProbes.gen.ts": render_kit_probes,
    "fleetEntities.gen.ts": render_fleet_entities,
    "kitDefs.gen.ts": render_kit_defs,
}


def rendered() -> dict[Path, str]:
    return {GEN_DIR / name: render() for name, render in sorted(TARGETS.items())}


def _read(path: Path) -> str:
    """Read a committed file, newline-agnostic.

    The repo runs with core.autocrlf=true on Windows, so a checked-out .gen.ts
    can arrive with CRLF. Line endings are not part of the entity contract:
    compare content, not whitespace policy.
    """
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def check() -> list[str]:
    """Return a human-readable diff per drifted file (empty list == in sync)."""
    problems: list[str] = []
    for path, want in rendered().items():
        rel = path.relative_to(REPO_ROOT).as_posix()
        if not path.exists():
            problems.append(f"{rel}: missing — run `python {_GENERATOR}`")
            continue
        have = _read(path)
        if have == want:
            continue
        diff = "".join(
            difflib.unified_diff(
                have.splitlines(keepends=True),
                want.splitlines(keepends=True),
                fromfile=f"{rel} (committed)",
                tofile=f"{rel} (generated from {_SOURCE})",
            )
        )
        problems.append(f"{rel}: out of date\n{diff}")
    return problems


def write() -> list[str]:
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    changed: list[str] = []
    for path, want in rendered().items():
        have = _read(path) if path.exists() else None
        if have == want:
            continue
        path.write_text(want, encoding="utf-8", newline="\n")
        changed.append(path.relative_to(REPO_ROOT).as_posix())
    return changed


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 with a diff when the committed TypeScript has drifted",
    )
    args = ap.parse_args(argv)

    if args.check:
        problems = check()
        if problems:
            sys.stderr.write(
                "Generated entity maps are out of date with "
                f"{_SOURCE}.\nRun `python {_GENERATOR}` and commit the result.\n\n"
            )
            for problem in problems:
                sys.stderr.write(problem + "\n")
            return 1
        print(f"entity maps in sync with {_SOURCE} ({len(TARGETS)} files)")
        return 0

    changed = write()
    if changed:
        for rel in changed:
            print(f"wrote {rel}")
    else:
        print("entity maps already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
