"""Hub Native API entity_id ↔ object_id maps (ingest + control proxy).

ESPHome 2026+ publishes name-slug object_ids (e.g. ``grow_mat_demand``,
``4_inch_intake_fan__main_``). Older firmware used internal C++ ids
(``growmat_demand``, ``fan_intake_main``). Ingest maps accept both; control
proxy uses the live slug the hub actually exposes.
"""

from __future__ import annotations

HUB_SWITCH_ENTITY_TO_OID: dict[str, str] = {
    "switch.dsc_hub_heater_demand": "heater_demand",
    "switch.dsc_hub_humidifier_demand": "humidifier_demand",
    "switch.dsc_hub_dehumidifier_demand": "dehumidifier_demand",
    "switch.dsc_hub_grow_mat_demand": "grow_mat_demand",
    "switch.dsc_hub_ac_demand": "ac_demand",
    "switch.dsc_hub_clone_humidifier_demand": "clone_humidifier_demand",
    "switch.dsc_hub_tent_full_auto_mode": "tent_full_auto_mode",
    "switch.dsc_hub_manual_takeover": "manual_takeover",
    "switch.dsc_hub_tent_manual_override": "tent_manual_override",
    "switch.dsc_hub_humidifier_intake_routing": "humidifier_intake_routing",
    "switch.dsc_hub_recirc_de_strat_pulse": "recirc_de-strat_pulse",
    "switch.dsc_hub_auto_photoperiod": "auto_photoperiod",
}

HUB_SWITCH_OID_TO_ENTITY: dict[str, str] = {
    "heater_demand": "switch.dsc_hub_heater_demand",
    "humidifier_demand": "switch.dsc_hub_humidifier_demand",
    "dehumidifier_demand": "switch.dsc_hub_dehumidifier_demand",
    "grow_mat_demand": "switch.dsc_hub_grow_mat_demand",
    "growmat_demand": "switch.dsc_hub_grow_mat_demand",
    "ac_demand": "switch.dsc_hub_ac_demand",
    "clone_humidifier_demand": "switch.dsc_hub_clone_humidifier_demand",
    "tent_full_auto_mode": "switch.dsc_hub_tent_full_auto_mode",
    "full_auto_switch": "switch.dsc_hub_tent_full_auto_mode",
    "manual_takeover": "switch.dsc_hub_manual_takeover",
    "manual_takeover_switch": "switch.dsc_hub_manual_takeover",
    "tent_manual_override": "switch.dsc_hub_tent_manual_override",
    "humidifier_intake_routing": "switch.dsc_hub_humidifier_intake_routing",
    "recirc_de-strat_pulse": "switch.dsc_hub_recirc_de_strat_pulse",
    "recirc_de_strat_pulse": "switch.dsc_hub_recirc_de_strat_pulse",
    "auto_photoperiod": "switch.dsc_hub_auto_photoperiod",
    "photoperiod_switch": "switch.dsc_hub_auto_photoperiod",
    # --- Informational (non-critical) hub switches — ingest only, no HUB_SWITCH_ENTITY_TO_OID
    # control proxy rows. Slug + legacy internal-id variants, same as the demand switches.
    "lock_wifi_ap": "switch.dsc_hub_lock_wifi_ap",
    "wifi_ap_lock": "switch.dsc_hub_lock_wifi_ap",
    "manual_light_hold": "switch.dsc_hub_manual_light_hold",
    "manual_light_hold_switch": "switch.dsc_hub_manual_light_hold",
    "humidifier_auto": "switch.dsc_hub_humidifier_auto",
    "humidifier_auto_switch": "switch.dsc_hub_humidifier_auto",
    "dehumidifier_auto": "switch.dsc_hub_dehumidifier_auto",
    "dehumidifier_auto_switch": "switch.dsc_hub_dehumidifier_auto",
    "heater_auto": "switch.dsc_hub_heater_auto",
    "heater_auto_switch": "switch.dsc_hub_heater_auto",
    "grow_mat_auto": "switch.dsc_hub_grow_mat_auto",
    "growmat_auto_switch": "switch.dsc_hub_grow_mat_auto",
    "ac_auto": "switch.dsc_hub_ac_auto",
    "ac_auto_switch": "switch.dsc_hub_ac_auto",
    "clone_humidifier_auto": "switch.dsc_hub_clone_humidifier_auto",
    "clone_hum_auto_switch": "switch.dsc_hub_clone_humidifier_auto",
    "mat_vote_pot_1": "switch.dsc_hub_mat_vote_pot_1",
    "mat_vote_1_switch": "switch.dsc_hub_mat_vote_pot_1",
    "mat_vote_pot_2": "switch.dsc_hub_mat_vote_pot_2",
    "mat_vote_2_switch": "switch.dsc_hub_mat_vote_pot_2",
    "mat_vote_pot_3": "switch.dsc_hub_mat_vote_pot_3",
    "mat_vote_3_switch": "switch.dsc_hub_mat_vote_pot_3",
    "mat_vote_pot_4": "switch.dsc_hub_mat_vote_pot_4",
    "mat_vote_4_switch": "switch.dsc_hub_mat_vote_pot_4",
    "ac_in_service": "switch.dsc_hub_ac_in_service",
    "ac_in_service_switch": "switch.dsc_hub_ac_in_service",
    "clone_humidifier_in_service": "switch.dsc_hub_clone_humidifier_in_service",
    "clone_hum_in_service_switch": "switch.dsc_hub_clone_humidifier_in_service",
    "pot1_in_service": "switch.dsc_hub_pot1_in_service",
    "pot1_in_service_switch": "switch.dsc_hub_pot1_in_service",
    "pot2_in_service": "switch.dsc_hub_pot2_in_service",
    "pot2_in_service_switch": "switch.dsc_hub_pot2_in_service",
    "pot3_in_service": "switch.dsc_hub_pot3_in_service",
    "pot3_in_service_switch": "switch.dsc_hub_pot3_in_service",
    "pot4_in_service": "switch.dsc_hub_pot4_in_service",
    "pot4_in_service_switch": "switch.dsc_hub_pot4_in_service",
}

HUB_NUMBER_ENTITY_TO_OID: dict[str, str] = {
    "number.dsc_hub_target_temp": "target_temp",
    "number.dsc_hub_rh_target_min": "rh_target_min",
    "number.dsc_hub_rh_target_max": "rh_target_max",
    "number.dsc_hub_vpd_target_min": "vpd_target_min",
    "number.dsc_hub_vpd_target_max": "vpd_target_max",
    "number.dsc_hub_clone_target_temp": "clone_target_temp",
    "number.dsc_hub_clone_rh_min": "clone_rh_min",
    "number.dsc_hub_clone_rh_max": "clone_rh_max",
    "number.dsc_hub_clone_vpd_min": "clone_vpd_min",
    "number.dsc_hub_clone_vpd_max": "clone_vpd_max",
    "number.dsc_hub_mat_root_zone_low": "mat_root-zone_low",
    "number.dsc_hub_mat_root_zone_high": "mat_root-zone_high",
    "number.dsc_hub_clone_light_hours": "clone_light_hours",
}

HUB_NUMBER_OID_TO_ENTITY: dict[str, str] = {
    "target_temp": "number.dsc_hub_target_temp",
    "rh_target_min": "number.dsc_hub_rh_target_min",
    "rh_target_max": "number.dsc_hub_rh_target_max",
    "vpd_target_min": "number.dsc_hub_vpd_target_min",
    "vpd_target_max": "number.dsc_hub_vpd_target_max",
    "clone_target_temp": "number.dsc_hub_clone_target_temp",
    "clone_rh_min": "number.dsc_hub_clone_rh_min",
    "clone_rh_max": "number.dsc_hub_clone_rh_max",
    "clone_vpd_min": "number.dsc_hub_clone_vpd_min",
    "clone_vpd_max": "number.dsc_hub_clone_vpd_max",
    "mat_root-zone_low": "number.dsc_hub_mat_root_zone_low",
    "mat_root-zone_high": "number.dsc_hub_mat_root_zone_high",
    "num_mat_rz_low": "number.dsc_hub_mat_root_zone_low",
    "num_mat_rz_high": "number.dsc_hub_mat_root_zone_high",
    "clone_light_hours": "number.dsc_hub_clone_light_hours",
    "num_clone_light_hours": "number.dsc_hub_clone_light_hours",
    # --- Informational (non-critical) hub numbers — ingest only (ladder waits,
    # min-off times, photoperiod ramp, fleet-heal targets). Slug + legacy id variants.
    "sunrise_duration": "number.dsc_hub_sunrise_duration",
    "num_sunrise": "number.dsc_hub_sunrise_duration",
    "sunset_duration": "number.dsc_hub_sunset_duration",
    "num_sunset": "number.dsc_hub_sunset_duration",
    "sf1000_target_brightness": "number.dsc_hub_sf1000_target_brightness",
    "num_sf1000_target": "number.dsc_hub_sf1000_target_brightness",
    "sf1000_ramp_floor": "number.dsc_hub_sf1000_ramp_floor",
    "num_sf_ramp_floor": "number.dsc_hub_sf1000_ramp_floor",
    "min_dark_hours": "number.dsc_hub_min_dark_hours",
    "num_min_dark_hours": "number.dsc_hub_min_dark_hours",
    "clone_hum_hysteresis": "number.dsc_hub_clone_hum_hysteresis",
    "num_clone_hum_hyst": "number.dsc_hub_clone_hum_hysteresis",
    "clone_hum_min_off-time": "number.dsc_hub_clone_hum_min_off_time",
    "num_clone_hum_min_off": "number.dsc_hub_clone_hum_min_off_time",
    "humidifier_min_off-time": "number.dsc_hub_humidifier_min_off_time",
    "num_hum_min_off": "number.dsc_hub_humidifier_min_off_time",
    "heater_min_off-time": "number.dsc_hub_heater_min_off_time",
    "num_heater_min_off": "number.dsc_hub_heater_min_off_time",
    "mat_min_off-time": "number.dsc_hub_mat_min_off_time",
    "num_mat_min_off": "number.dsc_hub_mat_min_off_time",
    "ladder_wait_dehum": "number.dsc_hub_ladder_wait_dehum",
    "num_ladder_wait_dehum": "number.dsc_hub_ladder_wait_dehum",
    "ladder-wait-dehum": "number.dsc_hub_ladder_wait_dehum",
    "ladder_wait_hum": "number.dsc_hub_ladder_wait_hum",
    "num_ladder_wait_hum": "number.dsc_hub_ladder_wait_hum",
    "ladder-wait-hum": "number.dsc_hub_ladder_wait_hum",
    "ladder_wait_heat": "number.dsc_hub_ladder_wait_heat",
    "num_ladder_wait_heat": "number.dsc_hub_ladder_wait_heat",
    "ladder-wait-heat": "number.dsc_hub_ladder_wait_heat",
    "ladder_wait_ac": "number.dsc_hub_ladder_wait_ac",
    "num_ladder_wait_ac": "number.dsc_hub_ladder_wait_ac",
    "ladder-wait-ac": "number.dsc_hub_ladder_wait_ac",
    "ladder_wait_mat": "number.dsc_hub_ladder_wait_mat",
    "num_ladder_wait_mat": "number.dsc_hub_ladder_wait_mat",
    "ladder-wait-mat": "number.dsc_hub_ladder_wait_mat",
    "de-strat_pulse_period": "number.dsc_hub_de_strat_pulse_period",
    "num_destrat_period": "number.dsc_hub_de_strat_pulse_period",
    "de-strat_pulse_length": "number.dsc_hub_de_strat_pulse_length",
    "num_destrat_burst": "number.dsc_hub_de_strat_pulse_length",
    "de-strat_pulse_level": "number.dsc_hub_de_strat_pulse_level",
    "num_destrat_level": "number.dsc_hub_de_strat_pulse_level",
    "ha_handshake": "number.dsc_hub_ha_handshake",
    "num_ha_handshake": "number.dsc_hub_ha_handshake",
    "vpd_band_target_hours": "number.dsc_hub_vpd_band_target_hours",
    "num_vpd_band_target_h": "number.dsc_hub_vpd_band_target_hours",
    "mister_target_hours": "number.dsc_hub_mister_target_hours",
    "num_mister_target_h": "number.dsc_hub_mister_target_hours",
    "mister_min_off_hours": "number.dsc_hub_mister_min_off_hours",
    "num_mister_min_off_h": "number.dsc_hub_mister_min_off_hours",
}

HUB_FAN_OID_TO_ENTITY: dict[str, str] = {
    "fan_intake_main": "fan.dsc_hub_4_inch_intake_fan_main",
    "4_inch_intake_fan__main_": "fan.dsc_hub_4_inch_intake_fan_main",
    "fan_intake_clone": "fan.dsc_hub_4_inch_intake_fan_2x4",
    "4_inch_intake_fan__2x4_": "fan.dsc_hub_4_inch_intake_fan_2x4",
    "fan_exhaust_recirc": "fan.dsc_hub_6_inch_exhaust_room",
    "6_inch_exhaust__room_": "fan.dsc_hub_6_inch_exhaust_room",
    "fan_exhaust_out": "fan.dsc_hub_6_inch_exhaust_outside",
    "6_inch_exhaust__outside_": "fan.dsc_hub_6_inch_exhaust_outside",
}

HUB_FAN_ENTITY_TO_OID: dict[str, str] = {
    "fan.dsc_hub_4_inch_intake_fan_main": "4_inch_intake_fan__main_",
    "fan.dsc_hub_4_inch_intake_fan_2x4": "4_inch_intake_fan__2x4_",
    "fan.dsc_hub_6_inch_exhaust_room": "6_inch_exhaust__room_",
    "fan.dsc_hub_6_inch_exhaust_outside": "6_inch_exhaust__outside_",
}

HUB_LIGHT_OID_TO_ENTITY: dict[str, str] = {
    "light_sf1000": "light.dsc_hub_sf1000_dimmer",
    "sf1000_dimmer": "light.dsc_hub_sf1000_dimmer",
}

HUB_LIGHT_ENTITY_TO_OID: dict[str, str] = {
    "light.dsc_hub_sf1000_dimmer": "sf1000_dimmer",
}

HUB_SELECT_OID_TO_ENTITY: dict[str, str] = {
    "control_strategy": "select.dsc_hub_control_strategy",
    "priority_tent_select": "select.dsc_hub_priority_tent",
    "priority_tent": "select.dsc_hub_priority_tent",
    "grow_stage": "select.dsc_hub_grow_stage",
    "clone_mode": "select.dsc_hub_clone_mode",
    "clone_photo_select": "select.dsc_hub_clone_photoperiod",
    "clone_photoperiod": "select.dsc_hub_clone_photoperiod",
}

HUB_SELECT_ENTITY_TO_OID: dict[str, str] = {
    "select.dsc_hub_control_strategy": "control_strategy",
    "select.dsc_hub_priority_tent": "priority_tent",
    "select.dsc_hub_grow_stage": "grow_stage",
    "select.dsc_hub_clone_mode": "clone_mode",
    "select.dsc_hub_clone_photoperiod": "clone_photoperiod",
}

# ESPHome object_id → hub.values metric key (exact match — id and name-slug variants)
HUB_SENSOR_OID_TO_KEY: dict[str, str] = {
    "temp_sensor": "temp_c",
    "tent_temperature": "temp_c",
    "humidity_sensor": "rh_pct",
    "tent_humidity": "rh_pct",
    "vpd_sensor": "vpd_kpa",
    "vpd_kpa": "vpd_kpa",
    "vpd__kpa_": "vpd_kpa",
    "room_temp": "room_temp_c",
    "room_temperature": "room_temp_c",
    "room_rh": "room_rh_pct",
    "room_humidity": "room_rh_pct",
    "clone_temp": "clone_temp_c",
    "clone_temperature": "clone_temp_c",
    "clone_rh": "clone_rh_pct",
    "clone_humidity": "clone_rh_pct",
    "clone_vpd": "clone_vpd_kpa",
    "clone_vpd_kpa": "clone_vpd_kpa",
    "clone_vpd__kpa_": "clone_vpd_kpa",
    "hub_heartbeat": "heartbeat",
    "heartbeat": "heartbeat",
    "uptime_s": "uptime",
    "uptime": "uptime",
    # Ladder fire countdowns
    "sens_hum_countdown": "humidifier_fire_countdown",
    "humidifier_fire_countdown": "humidifier_fire_countdown",
    "sens_dehum_countdown": "dehumidifier_fire_countdown",
    "dehumidifier_fire_countdown": "dehumidifier_fire_countdown",
    "sens_heater_countdown": "heater_fire_countdown",
    "heater_fire_countdown": "heater_fire_countdown",
    "sens_ac_countdown": "ac_fire_countdown",
    "ac_fire_countdown": "ac_fire_countdown",
    "sens_mat_countdown": "grow_mat_fire_countdown",
    "grow_mat_fire_countdown": "grow_mat_fire_countdown",
    "sens_clone_hum_countdown": "clone_humidifier_fire_countdown",
    "clone_humidifier_fire_countdown": "clone_humidifier_fire_countdown",
    # Ladder cooldown remaining
    "sens_hum_cooldown": "humidifier_cooldown_remaining",
    "humidifier_cooldown_remaining": "humidifier_cooldown_remaining",
    "sens_dehum_cooldown": "dehumidifier_cooldown_remaining",
    "dehumidifier_cooldown_remaining": "dehumidifier_cooldown_remaining",
    "sens_heater_cooldown": "heater_cooldown_remaining",
    "heater_cooldown_remaining": "heater_cooldown_remaining",
    "sens_ac_cooldown": "ac_cooldown_remaining",
    "ac_cooldown_remaining": "ac_cooldown_remaining",
    "sens_mat_cooldown": "grow_mat_cooldown_remaining",
    "grow_mat_cooldown_remaining": "grow_mat_cooldown_remaining",
    "sens_clone_hum_cooldown": "clone_humidifier_cooldown_remaining",
    "clone_humidifier_cooldown_remaining": "clone_humidifier_cooldown_remaining",
    # --- Informational (non-critical) diagnostics — WiFi/link health, light debt,
    # CO2 estimate, fleet-heal band/mister accounting. Slug + legacy id variants.
    "wifi_rssi": "wifi_rssi",
    "api_down_age": "api_down_age",
    "api_down_age_s": "api_down_age",
    "ha_handshake_age": "ha_handshake_age",
    "ha_handshake_age_s": "ha_handshake_age",
    "link_recovery_bounces": "link_recovery_bounces",
    "link_rec_bounce_count": "link_recovery_bounces",
    "light_delivered_hours": "light_delivered_hours",
    "light_delivered_h": "light_delivered_hours",
    "light_debt_hours": "light_debt_hours",
    "light_debt_h": "light_debt_hours",
    "co2_sensor_voltage": "co2_sensor_voltage",
    "co2_voltage": "co2_sensor_voltage",
    "dynamic_co2_ppm": "dynamic_co2_ppm",
    "co2_ppm_estimate": "dynamic_co2_ppm",
    "vpd_main_band_hours": "vpd_main_band_hours",
    "vpd_main_band_h": "vpd_main_band_hours",
    "vpd_clone_band_hours": "vpd_clone_band_hours",
    "vpd_clone_band_h": "vpd_clone_band_hours",
    "vpd_main_band_debt_hours": "vpd_main_band_debt_hours",
    "vpd_main_debt_h": "vpd_main_band_debt_hours",
    "vpd_clone_band_debt_hours": "vpd_clone_band_debt_hours",
    "vpd_clone_debt_h": "vpd_clone_band_debt_hours",
    "mister_delivered_hours": "mister_delivered_hours",
    "mister_delivered_h": "mister_delivered_hours",
    "mister_debt_hours": "mister_debt_hours",
    "mister_debt_h": "mister_debt_hours",
    "coherence_hash": "coherence_hash",
    "coherence_hash_s": "coherence_hash",
    "coherence_epoch": "coherence_epoch",
    "coherence_epoch_s": "coherence_epoch",
}

HUB_BINARY_OID_TO_ENTITY: dict[str, str] = {
    "main_window_bs": "binary_sensor.dsc_hub_4x8_window_open",
    "4x8_window_open": "binary_sensor.dsc_hub_4x8_window_open",
    "clone_window_bs": "binary_sensor.dsc_hub_2x4_window_open",
    "2x4_window_open": "binary_sensor.dsc_hub_2x4_window_open",
    "light_catchup_bs": "binary_sensor.dsc_hub_light_catchup_active",
    "light_catchup_active": "binary_sensor.dsc_hub_light_catchup_active",
    "rootzone_fault_bs": "binary_sensor.dsc_hub_root_zone_sensor_fault",
    "root_zone_sensor_fault": "binary_sensor.dsc_hub_root_zone_sensor_fault",
    "root-zone_sensor_fault": "binary_sensor.dsc_hub_root_zone_sensor_fault",
    "emergency_failsafe": "binary_sensor.dsc_hub_emergency_failsafe",
    "climate_sensor_fault": "binary_sensor.dsc_hub_climate_sensor_fault",
    "aux_sensor_fault": "binary_sensor.dsc_hub_aux_sensor_fault",
    "coherence_mismatch": "binary_sensor.dsc_hub_coherence_mismatch",
    "coherence_mismatch_bs": "binary_sensor.dsc_hub_coherence_mismatch",
    "pot1_espnow_link": "binary_sensor.dsc_hub_pot1_esp_now_link",
    "pot1_esp_now_link": "binary_sensor.dsc_hub_pot1_esp_now_link",
    "pot1_esp-now_link": "binary_sensor.dsc_hub_pot1_esp_now_link",
    "pot2_espnow_link": "binary_sensor.dsc_hub_pot2_esp_now_link",
    "pot2_esp_now_link": "binary_sensor.dsc_hub_pot2_esp_now_link",
    "pot2_esp-now_link": "binary_sensor.dsc_hub_pot2_esp_now_link",
    "pot3_espnow_link": "binary_sensor.dsc_hub_pot3_esp_now_link",
    "pot3_esp_now_link": "binary_sensor.dsc_hub_pot3_esp_now_link",
    "pot3_esp-now_link": "binary_sensor.dsc_hub_pot3_esp_now_link",
    "pot4_espnow_link": "binary_sensor.dsc_hub_pot4_esp_now_link",
    "pot4_esp_now_link": "binary_sensor.dsc_hub_pot4_esp_now_link",
    "pot4_esp-now_link": "binary_sensor.dsc_hub_pot4_esp_now_link",
    # --- Informational (non-critical) link/heal diagnostics — not in any alert list.
    "ha_link_status": "binary_sensor.dsc_hub_ha_link_status",
    "ha_connected": "binary_sensor.dsc_hub_ha_link_status",
    "wifi_associated": "binary_sensor.dsc_hub_wifi_associated",
    "clock_valid": "binary_sensor.dsc_hub_clock_valid",
    "clock_valid_bs": "binary_sensor.dsc_hub_clock_valid",
    "fix_active": "binary_sensor.dsc_hub_fix_active",
    "fix_active_bs": "binary_sensor.dsc_hub_fix_active",
    "ota_blocked": "binary_sensor.dsc_hub_ota_blocked",
    "ota_blocked_bs": "binary_sensor.dsc_hub_ota_blocked",
    "mister_catchup_active": "binary_sensor.dsc_hub_mister_catchup_active",
    "mister_catchup_bs": "binary_sensor.dsc_hub_mister_catchup_active",
    "learning_paused": "binary_sensor.dsc_hub_learning_paused",
    "learning_paused_bs": "binary_sensor.dsc_hub_learning_paused",
}

# Text sensor object_id → fleet.values key (firmware string, not float)
HUB_TEXT_SENSOR_OID_TO_KEY: dict[str, str] = {
    "firmware_version": "firmware_version",
    "rf_status": "rf_status",
    # --- Informational network/heal strings (wifi_info platform + fleet-heal).
    "ip_address": "ip_address",
    "network_ip": "ip_address",
    "wifi_ssid": "wifi_ssid",
    "network_ssid": "wifi_ssid",
    "wifi_bssid": "wifi_bssid",
    "network_bssid": "wifi_bssid",
    "esphome_version": "esphome_version",
    "link_recovery_last_reason": "link_recovery_last_reason",
    "link_rec_last_reason": "link_recovery_last_reason",
    "last_evt": "last_evt",
    "last_evt_ts": "last_evt",
}
