"""Generate frontend/src/iconSet.ts from the DSC-HUB Cultivation Icons pack.

Source of truth: docs/design/icons/dsc-hub-icons-v5/svg-24/*.svg (+ index.json for
category / label). The SVGs use `currentColor` for every stroke and fill, so the SPA
tints them with CSS `color` alone (see `.dsc-icon--*` and `.dsc-icon.is-oos` in dsc.css).

Run from the repo root:  python scripts/gen-dsc-hub-icons.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACK = ROOT / "docs/design/icons/dsc-hub-icons-v5"
OUT = ROOT / "frontend/src/iconSet.ts"


def normalize(svg: str) -> str:
    svg = svg.lstrip("﻿").strip()
    svg = re.sub(r"\s+", " ", svg)
    svg = re.sub(r"> <", "><", svg)

    def fix_root(m: re.Match[str]) -> str:
        tag = m.group(0)
        tag = re.sub(r'(?<![-\w])width="[^"]*"', 'width="100%"', tag, count=1)
        tag = re.sub(r'(?<![-\w])height="[^"]*"', 'height="100%"', tag, count=1)
        if 'aria-hidden="true"' not in tag:
            tag = tag[:-1] + ' aria-hidden="true">'
        return tag

    return re.sub(r"<svg\b[^>]*>", fix_root, svg, count=1)


def main() -> None:
    index = json.loads((PACK / "index.json").read_text(encoding="utf-8"))
    meta = {i["name"]: i for i in index["icons"]}
    files = sorted((PACK / "svg-24").glob("*.svg"))
    names = [f.stem for f in files]
    missing = sorted(set(meta) - set(names))
    extra = sorted(set(names) - set(meta))
    if missing or extra:
        raise SystemExit(f"index/svg mismatch — missing svg: {missing}; not in index: {extra}")
    bad = [f.stem for f in files if re.search(r'(stroke|fill)="#', f.read_text(encoding="utf-8"))]
    if bad:
        raise SystemExit(f"hard-coded colours (must be currentColor): {bad}")

    lines = [
        "/** Auto-generated by scripts/gen-dsc-hub-icons.py from docs/design/icons/dsc-hub-icons-v5 — do not edit. */",
        "/* eslint-disable */",
        f"/** DSC-HUB Cultivation Icons {index['version']} — {len(files)} mono line icons (24 px, 1.5 px stroke, currentColor). */",
        "export const ICON_SVG_SET = {",
    ]
    for f in files:
        lines.append(f"  {json.dumps(f.stem)}: {json.dumps(normalize(f.read_text(encoding='utf-8')))},")
    lines.append("} as const;")
    lines.append("")
    lines.append("export type IconNameSet = keyof typeof ICON_SVG_SET;")
    lines.append("")
    lines.append("/** Category + human label per icon, from the pack's index.json (categories from the gallery). */")
    lines.append("export const ICON_META_SET: Record<IconNameSet, { category: string; label: string }> = {")
    for f in files:
        m = meta[f.stem]
        lines.append(f"  {json.dumps(f.stem)}: {{ category: {json.dumps(m['category'])}, label: {json.dumps(m['label'])} }},")
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(files)} icons, {OUT.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
