#!/usr/bin/env python3
"""Generate homeassistant/packages/dsc_v4_build_plant.yaml (single domain keys)."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "homeassistant" / "packages" / "dsc_v4_build_plant.yaml"


def roster_text() -> str:
    lines = []
    for i in range(1, 9):
        for field, maxlen, label in (
            ("nickname", 64, "Nickname"),
            ("strain", 64, "Strain"),
            ("blend", 255, "Blend"),
            ("recipe", 255, "Recipe"),
            ("notes", 255, "Notes"),
        ):
            lines.append(
                f"""  dsc_plant_roster_{i}_{field}:
    name: "DSC Roster {i} {label}"
    max: {maxlen}
    initial: ""
"""
            )
    return "".join(lines)


def roster_number() -> str:
    lines = []
    for i in range(1, 9):
        lines.append(
            f"""  dsc_plant_roster_{i}_seed_count:
    name: "DSC Roster {i} Seed Count"
    min: 0
    max: 1000
    step: 1
    initial: 0
    mode: box
"""
        )
    return "".join(lines)


def roster_datetime() -> str:
    lines = []
    for i in range(1, 9):
        lines.append(
            f"""  dsc_plant_roster_{i}_sprout:
    name: "DSC Roster {i} Sprout"
    has_date: true
    has_time: false
"""
        )
    return "".join(lines)


def roster_select() -> str:
    lines = []
    for i in range(1, 9):
        lines.append(
            f"""  dsc_plant_roster_{i}_pot:
    name: "DSC Roster {i} Pot"
    options: ["none", "1", "2", "3", "4"]
    initial: "none"
  dsc_plant_roster_{i}_status:
    name: "DSC Roster {i} Status"
    options: ["empty", "stock", "active", "done"]
    initial: "empty"
"""
        )
    return "".join(lines)


def want_climate(pot: int) -> str:
    # HA 2026.8 rejects non-numeric states on sensors with unit_of_measurement.
    # Use 0 as the unset sentinel (Apply Climate already treats 0 as skip).
    return f"""
      - name: "DSC POT{pot} Want Temp Min"
        unique_id: dsc_pot{pot}_want_temp_min
        unit_of_measurement: "°C"
        state: >
          {{% set s = states('select.dsc_pot_{pot}_strain') %}}
          {{% if s in ['unknown','unavailable',''] %}}{{% set s = states('select.dsc_pot{pot}_strain') %}}{{% endif %}}
          {{% if s in ['unknown','unavailable',''] %}}{{% set s = states('input_select.dsc_pot{pot}_strain') %}}{{% endif %}}
          {{% if s.startswith('Custom') %}}
            {{{{ states('input_number.dsc_custom_strain_' ~ s.split(' ')[1] ~ '_temp_min')|float(0) }}}}
          {{% else %}}0{{% endif %}}
      - name: "DSC POT{pot} Want Temp Max"
        unique_id: dsc_pot{pot}_want_temp_max
        unit_of_measurement: "°C"
        state: >
          {{% set s = states('select.dsc_pot_{pot}_strain') %}}
          {{% if s in ['unknown','unavailable',''] %}}{{% set s = states('select.dsc_pot{pot}_strain') %}}{{% endif %}}
          {{% if s in ['unknown','unavailable',''] %}}{{% set s = states('input_select.dsc_pot{pot}_strain') %}}{{% endif %}}
          {{% if s.startswith('Custom') %}}
            {{{{ states('input_number.dsc_custom_strain_' ~ s.split(' ')[1] ~ '_temp_max')|float(0) }}}}
          {{% else %}}0{{% endif %}}
      - name: "DSC POT{pot} Want RH Min"
        unique_id: dsc_pot{pot}_want_rh_min
        unit_of_measurement: "%"
        state: >
          {{% set s = states('select.dsc_pot_{pot}_strain') %}}
          {{% if s in ['unknown','unavailable',''] %}}{{% set s = states('select.dsc_pot{pot}_strain') %}}{{% endif %}}
          {{% if s in ['unknown','unavailable',''] %}}{{% set s = states('input_select.dsc_pot{pot}_strain') %}}{{% endif %}}
          {{% if s.startswith('Custom') %}}
            {{{{ states('input_number.dsc_custom_strain_' ~ s.split(' ')[1] ~ '_rh_min')|float(0) }}}}
          {{% else %}}0{{% endif %}}
      - name: "DSC POT{pot} Want RH Max"
        unique_id: dsc_pot{pot}_want_rh_max
        unit_of_measurement: "%"
        state: >
          {{% set s = states('select.dsc_pot_{pot}_strain') %}}
          {{% if s in ['unknown','unavailable',''] %}}{{% set s = states('select.dsc_pot{pot}_strain') %}}{{% endif %}}
          {{% if s in ['unknown','unavailable',''] %}}{{% set s = states('input_select.dsc_pot{pot}_strain') %}}{{% endif %}}
          {{% if s.startswith('Custom') %}}
            {{{{ states('input_number.dsc_custom_strain_' ~ s.split(' ')[1] ~ '_rh_max')|float(0) }}}}
          {{% else %}}0{{% endif %}}
"""


def main() -> None:
    want = "".join(want_climate(p) for p in (1, 2, 3, 4))
    text = f"""# ==================================================================
#  DSC-HUB · BUILD A PLANT (separate product surface)
#  ------------------------------------------------------------------
#  Soil % blend · plant roster inventory · mix calculator glue ·
#  Apply climate Want from custom temp/RH (N-055). Metric only.
#  Does not invent catalog climate bands or PPFD grids.
#  Generated by scripts/gen_dsc_v4_build_plant.py — prefer editing that.
# ==================================================================

input_text:
  dsc_build_nickname:
    name: "DSC Build Plant Nickname"
    max: 64
    initial: ""
  dsc_build_strain:
    name: "DSC Build Plant Strain"
    max: 64
    initial: ""
  dsc_build_recipe_note:
    name: "DSC Build Recipe Note"
    max: 255
    initial: ""
  dsc_build_blend_snapshot:
    name: "DSC Build Blend Snapshot"
    max: 255
    initial: ""
  dsc_blend_component_1_name:
    name: "DSC Blend Component 1"
    max: 64
    initial: "CANNA Coco Professional Plus"
  dsc_blend_component_2_name:
    name: "DSC Blend Component 2"
    max: 64
    initial: ""
  dsc_blend_component_3_name:
    name: "DSC Blend Component 3"
    max: 64
    initial: ""
{roster_text()}
input_datetime:
  dsc_build_sprout_date:
    name: "DSC Build Sprout Date"
    has_date: true
    has_time: false
{roster_datetime()}
input_number:
{roster_number()}
  dsc_blend_pct_1:
    name: "DSC Blend % 1"
    min: 0
    max: 100
    step: 1
    initial: 100
    unit_of_measurement: "%"
    mode: slider
  dsc_blend_pct_2:
    name: "DSC Blend % 2"
    min: 0
    max: 100
    step: 1
    initial: 0
    unit_of_measurement: "%"
    mode: slider
  dsc_blend_pct_3:
    name: "DSC Blend % 3"
    min: 0
    max: 100
    step: 1
    initial: 0
    unit_of_measurement: "%"
    mode: slider
  dsc_blend_total_l:
    name: "DSC Blend Total Volume"
    min: 1
    max: 200
    step: 0.5
    initial: 20
    unit_of_measurement: "L"
    mode: box

input_select:
  dsc_build_custom_slot:
    name: "DSC Build Custom Strain Slot"
    icon: mdi:database-edit
    options: ["auto", "1", "2", "3", "4", "5"]
    initial: "auto"
  dsc_build_assign_pot:
    name: "DSC Build Assign Pot"
    icon: mdi:flower
    options:
      - "none"
      - "1"
      - "2"
      - "3"
      - "4"
    initial: "none"
  dsc_build_climate_pot:
    name: "DSC Build Climate Apply Pot"
    icon: mdi:thermometer
    options:
      - "Fleet"
      - "1"
      - "2"
      - "3"
      - "4"
    initial: "Fleet"
{roster_select()}
input_boolean:
  dsc_build_status_ready:
    name: "DSC Build Status Ready"
    initial: true

template:
  - sensor:
      - name: "DSC Blend Summary"
        unique_id: dsc_blend_summary
        icon: mdi:layers-triple
        unit_of_measurement: "%"
        state: >
          {{% set p1 = states('input_number.dsc_blend_pct_1')|float(0) %}}
          {{% set p2 = states('input_number.dsc_blend_pct_2')|float(0) %}}
          {{% set p3 = states('input_number.dsc_blend_pct_3')|float(0) %}}
          {{{{ (p1 + p2 + p3)|round(0) }}}}
        attributes:
          valid: >
            {{{{ (states('input_number.dsc_blend_pct_1')|float(0)
                + states('input_number.dsc_blend_pct_2')|float(0)
                + states('input_number.dsc_blend_pct_3')|float(0))|round(0) == 100 }}}}
          total_l: "{{{{ states('input_number.dsc_blend_total_l') }}}}"
          components: >
            {{% set L = states('input_number.dsc_blend_total_l')|float(20) %}}
            {{% set parts = [] %}}
            {{% for n in [1,2,3] %}}
              {{% set name = states('input_text.dsc_blend_component_' ~ n ~ '_name')|trim %}}
              {{% set pct = states('input_number.dsc_blend_pct_' ~ n)|float(0) %}}
              {{% if name and pct > 0 %}}
                {{% set litres = (pct / 100 * L)|round(2) %}}
                {{% set parts = parts + [{{'slot': n, 'name': name, 'pct': pct, 'litres': litres}}] %}}
              {{% endif %}}
            {{% endfor %}}
            {{{{ parts }}}}
          bar: >
            {{% set parts = [] %}}
            {{% for n in [1,2,3] %}}
              {{% set name = states('input_text.dsc_blend_component_' ~ n ~ '_name')|trim %}}
              {{% set pct = states('input_number.dsc_blend_pct_' ~ n)|float(0) %}}
              {{% if pct > 0 %}}
                {{% set parts = parts + [ (name or ('#' ~ n)) ~ ' ' ~ pct|round(0) ~ '%' ] %}}
              {{% endif %}}
            {{% endfor %}}
            {{{{ parts|join(' · ') }}}}

      - name: "DSC Mix Calculator"
        unique_id: dsc_mix_calculator
        icon: mdi:calculator-variant
        state: >
          {{% set L = states('input_number.dsc_mix_tank_liters')|float(20) %}}
          {{% set str = states('input_number.dsc_mix_strength_pct')|float(100) / 100 %}}
          {{% set lines = [] %}}
          {{% set total = namespace(v=0) %}}
          {{% set short = namespace(v=false) %}}
          {{% for n in range(1,9) %}}
            {{% set name = states('input_text.dsc_nutrient_' ~ n ~ '_name')|trim %}}
            {{% set dose = states('input_number.dsc_nutrient_' ~ n ~ '_dose_ml_l')|float(0) %}}
            {{% if name and dose > 0 %}}
              {{% set ml = (dose * L * str)|round(1) %}}
              {{% set total.v = total.v + ml %}}
              {{% set inv = is_state('input_boolean.dsc_nutrient_' ~ n ~ '_in_inventory','on') %}}
              {{% set stock = states('input_number.dsc_nutrient_' ~ n ~ '_stock_ml')|float(0) %}}
              {{% if inv and stock < ml %}}{{% set short.v = true %}}{{% endif %}}
              {{% set lines = lines + [name ~ ': ' ~ ml ~ ' ml @ ' ~ dose ~ ' ml/L'] %}}
            {{% endif %}}
          {{% endfor %}}
          {{{{ ((total.v|round(1) ~ ' ml total') ~ (' - SHORT STOCK' if short.v else '')) if lines else 'No doses set' }}}}
        attributes:
          tank_l: "{{{{ states('input_number.dsc_mix_tank_liters') }}}}"
          strength_pct: "{{{{ states('input_number.dsc_mix_strength_pct') }}}}"
          lines: >
            {{% set L = states('input_number.dsc_mix_tank_liters')|float(20) %}}
            {{% set str = states('input_number.dsc_mix_strength_pct')|float(100) / 100 %}}
            {{% set out = [] %}}
            {{% for n in range(1,9) %}}
              {{% set name = states('input_text.dsc_nutrient_' ~ n ~ '_name')|trim %}}
              {{% set dose = states('input_number.dsc_nutrient_' ~ n ~ '_dose_ml_l')|float(0) %}}
              {{% set stock = states('input_number.dsc_nutrient_' ~ n ~ '_stock_ml')|float(0) %}}
              {{% set inv = is_state('input_boolean.dsc_nutrient_' ~ n ~ '_in_inventory','on') %}}
              {{% if name and dose > 0 %}}
                {{% set ml = (dose * L * str)|round(1) %}}
                {{% set out = out + [{{'slot': n, 'name': name, 'dose_ml_l': dose, 'ml': ml, 'stock_ml': stock, 'in_inventory': inv, 'short_stock': inv and stock < ml}}] %}}
              {{% endif %}}
            {{% endfor %}}
            {{{{ out }}}}
          short_stock_any: >
            {{% set L = states('input_number.dsc_mix_tank_liters')|float(20) %}}
            {{% set str = states('input_number.dsc_mix_strength_pct')|float(100) / 100 %}}
            {{% set ns = namespace(short=false) %}}
            {{% for n in range(1,9) %}}
              {{% set dose = states('input_number.dsc_nutrient_' ~ n ~ '_dose_ml_l')|float(0) %}}
              {{% set ml = dose * L * str %}}
              {{% if is_state('input_boolean.dsc_nutrient_' ~ n ~ '_in_inventory','on')
                    and states('input_text.dsc_nutrient_' ~ n ~ '_name')|trim
                    and dose > 0
                    and states('input_number.dsc_nutrient_' ~ n ~ '_stock_ml')|float(0) < ml %}}
                {{% set ns.short = true %}}
              {{% endif %}}
            {{% endfor %}}
            {{{{ ns.short }}}}
          total_ml: >
            {{% set L = states('input_number.dsc_mix_tank_liters')|float(20) %}}
            {{% set str = states('input_number.dsc_mix_strength_pct')|float(100) / 100 %}}
            {{% set t = namespace(v=0) %}}
            {{% for n in range(1,9) %}}
              {{% set name = states('input_text.dsc_nutrient_' ~ n ~ '_name')|trim %}}
              {{% set dose = states('input_number.dsc_nutrient_' ~ n ~ '_dose_ml_l')|float(0) %}}
              {{% if name and dose > 0 %}}
                {{% set t.v = t.v + (dose * L * str) %}}
              {{% endif %}}
            {{% endfor %}}
            {{{{ t.v|round(1) }}}}
          note: "Metric ml for tank L × strength%. Accept mix burns stock via script.dsc_accept_mix."

      - name: "DSC Plant Roster Summary"
        unique_id: dsc_plant_roster_summary
        icon: mdi:sprout
        state: >
          {{% set n = namespace(v=0) %}}
          {{% for i in range(1,9) %}}
            {{% if states('input_select.dsc_plant_roster_' ~ i ~ '_status') not in ['empty','unknown','unavailable'] %}}
              {{% set n.v = n.v + 1 %}}
            {{% endif %}}
          {{% endfor %}}
          {{{{ n.v }}}} occupied
        attributes:
          slots: >
            {{% set out = [] %}}
            {{% for i in range(1,9) %}}
              {{% set st = states('input_select.dsc_plant_roster_' ~ i ~ '_status') %}}
              {{% if st not in ['empty','unknown','unavailable'] %}}
                {{% set out = out + [{{
                  'slot': i,
                  'nickname': states('input_text.dsc_plant_roster_' ~ i ~ '_nickname'),
                  'strain': states('input_text.dsc_plant_roster_' ~ i ~ '_strain'),
                  'blend': states('input_text.dsc_plant_roster_' ~ i ~ '_blend'),
                  'recipe': states('input_text.dsc_plant_roster_' ~ i ~ '_recipe'),
                  'sprout': states('input_datetime.dsc_plant_roster_' ~ i ~ '_sprout'),
                  'pot': states('input_select.dsc_plant_roster_' ~ i ~ '_pot'),
                  'status': st,
                  'seed_count': states('input_number.dsc_plant_roster_' ~ i ~ '_seed_count')|int(0),
                  'notes': states('input_text.dsc_plant_roster_' ~ i ~ '_notes')
                }}] %}}
              {{% endif %}}
            {{% endfor %}}
            {{{{ out }}}}
{want}
script:
  dsc_build_plant_commit:
    alias: "DSC Build Plant · Commit to roster"
    description: "Write active builder fields into the next empty roster slot."
    mode: single
    sequence:
      - variables:
          slot: >
            {{% set ns = namespace(s=0) %}}
            {{% for i in range(1,9) %}}
              {{% if ns.s == 0 and states('input_select.dsc_plant_roster_' ~ i ~ '_status') in ['empty','unknown','unavailable',''] %}}
                {{% set ns.s = i %}}
              {{% endif %}}
            {{% endfor %}}
            {{{{ ns.s }}}}
          snap: >
            {{% set parts = [] %}}
            {{% for n in [1,2,3] %}}
              {{% set name = states('input_text.dsc_blend_component_' ~ n ~ '_name')|trim %}}
              {{% set pct = states('input_number.dsc_blend_pct_' ~ n)|float(0) %}}
              {{% if name and pct > 0 %}}{{% set parts = parts + [name ~ ' ' ~ pct|round(0) ~ '%'] %}}{{% endif %}}
            {{% endfor %}}
            {{{{ parts|join(' + ') }}}}
      - choose:
          - conditions:
              - condition: template
                value_template: "{{{{ slot|int(0) == 0 }}}}"
            sequence:
              - action: persistent_notification.create
                data:
                  title: "Build a Plant · roster full"
                  message: "All eight roster slots are occupied. Clear a slot before committing. Plant was not seated."
              - stop: "Roster full — commit no-op"
                error: true
      - action: input_text.set_value
        target:
          entity_id: "input_text.dsc_plant_roster_{{{{ slot }}}}_nickname"
        data:
          value: "{{{{ states('input_text.dsc_build_nickname') }}}}"
      - action: input_text.set_value
        target:
          entity_id: "input_text.dsc_plant_roster_{{{{ slot }}}}_strain"
        data:
          value: "{{{{ states('input_text.dsc_build_strain') }}}}"
      - action: input_text.set_value
        target:
          entity_id: "input_text.dsc_plant_roster_{{{{ slot }}}}_blend"
        data:
          value: "{{{{ snap }}}}"
      - action: input_text.set_value
        target:
          entity_id: "input_text.dsc_plant_roster_{{{{ slot }}}}_recipe"
        data:
          value: "{{{{ states('input_text.dsc_build_recipe_note') or states('sensor.dsc_mix_calculator') }}}}"
      - action: input_text.set_value
        target:
          entity_id: input_text.dsc_build_blend_snapshot
        data:
          value: "{{{{ snap }}}}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{{{ states('input_datetime.dsc_build_sprout_date') not in ['unknown','unavailable',''] }}}}"
            sequence:
              - action: input_datetime.set_datetime
                target:
                  entity_id: "input_datetime.dsc_plant_roster_{{{{ slot }}}}_sprout"
                data:
                  date: "{{{{ states('input_datetime.dsc_build_sprout_date')[:10] }}}}"
      - action: input_select.select_option
        target:
          entity_id: "input_select.dsc_plant_roster_{{{{ slot }}}}_pot"
        data:
          option: "{{{{ states('input_select.dsc_build_assign_pot') }}}}"
      - action: input_select.select_option
        target:
          entity_id: "input_select.dsc_plant_roster_{{{{ slot }}}}_status"
        data:
          option: "{{{{ 'active' if states('input_select.dsc_build_assign_pot') != 'none' else 'stock' }}}}"
      - action: persistent_notification.create
        data:
          title: "Build a Plant · committed"
          message: "Roster slot {{{{ slot }}}} ← {{{{ states('input_text.dsc_build_nickname') or states('input_text.dsc_build_strain') }}}}"

  dsc_plant_assign_to_pot:
    alias: "DSC Build Plant · Assign to pot"
    description: "Resolve catalog/custom strain, write both pot ID forms, and activate the matching roster entry."
    mode: single
    fields:
      pot:
        name: Pot
        description: "1–4"
        example: "1"
        required: false
        selector:
          select:
            options: ["1", "2", "3", "4"]
    sequence:
      - variables:
          n: "{{{{ (pot if pot is defined and pot|string|trim else states('input_select.dsc_build_assign_pot'))|string|trim }}}}"
          strain: "{{{{ states('input_text.dsc_build_strain')|trim }}}}"
          nickname: "{{{{ states('input_text.dsc_build_nickname')|trim or states('input_text.dsc_build_strain')|trim }}}}"
          sprout: "{{{{ states('input_datetime.dsc_build_sprout_date')[:10] }}}}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{{{ n not in ['1','2','3','4'] }}}}"
            sequence:
              - action: persistent_notification.create
                data:
                  title: "Build a Plant · assignment failed"
                  message: "Select a valid pot (1-4) before assigning."
              - stop: "No valid pot selected"
                error: true
          - conditions:
              - condition: template
                value_template: "{{{{ strain == '' }}}}"
            sequence:
              - action: persistent_notification.create
                data:
                  title: "Build a Plant · assignment failed"
                  message: "Strain is empty. Pick or enter a strain first."
              - stop: "Strain is empty"
                error: true
      - variables:
          direct_strain: "{{{{ strain in ['Generic Photoperiod','Generic Autoflower','Custom 1','Custom 2','Custom 3','Custom 4','Custom 5'] }}}}"
          custom_slot: >
            {{% if strain in ['Generic Photoperiod','Generic Autoflower','Custom 1','Custom 2','Custom 3','Custom 4','Custom 5'] %}}
              0
            {{% elif states('input_select.dsc_build_custom_slot') in ['1','2','3','4','5'] %}}
              {{{{ states('input_select.dsc_build_custom_slot') }}}}
            {{% else %}}
              {{% set ns = namespace(slot=0) %}}
              {{% for i in [1,2,3,4,5] %}}
                {{% set current = states('input_text.dsc_custom_strain_' ~ i ~ '_name')|trim %}}
                {{% if ns.slot == 0 and (current == '' or current in ['unknown','unavailable'] or current == strain) %}}
                  {{% set ns.slot = i %}}
                {{% endif %}}
              {{% endfor %}}
              {{{{ ns.slot }}}}
            {{% endif %}}
          roster_slot: >
            {{% set ns = namespace(slot=0) %}}
            {{% for i in range(1,9) %}}
              {{% set rs = states('input_text.dsc_plant_roster_' ~ i ~ '_strain')|trim %}}
              {{% set rn = states('input_text.dsc_plant_roster_' ~ i ~ '_nickname')|trim %}}
              {{% if ns.slot == 0 and (rs == strain or (nickname and rn == nickname)) %}}
                {{% set ns.slot = i %}}
              {{% endif %}}
            {{% endfor %}}
            {{{{ ns.slot }}}}
      - choose:
          - conditions:
              - condition: template
                value_template: "{{{{ not direct_strain and custom_slot|int(0) == 0 }}}}"
            sequence:
              - action: persistent_notification.create
                data:
                  title: "Build a Plant · assignment failed"
                  message: "All five custom strain slots are occupied. Choose a slot explicitly or clear one."
              - stop: "No custom strain slot available"
                error: true
      - variables:
          strain_option: "{{{{ strain if direct_strain else 'Custom ' ~ custom_slot }}}}"
      - action: text.set_value
        target:
          entity_id: "text.dsc_pot{{{{ n }}}}_plant_name"
        data:
          value: "{{{{ nickname }}}}"
        continue_on_error: true
      - action: text.set_value
        target:
          entity_id: "text.dsc_pot_{{{{ n }}}}_plant_name"
        data:
          value: "{{{{ nickname }}}}"
        continue_on_error: true
      - choose:
          - conditions:
              - condition: template
                value_template: "{{{{ not direct_strain }}}}"
            sequence:
              - variables:
                  existing_custom: "{{{{ states('input_text.dsc_custom_strain_' ~ custom_slot ~ '_name')|trim }}}}"
              - choose:
                  - conditions:
                      - condition: template
                        value_template: >-
                          {{{{ existing_custom not in ['', 'unknown', 'unavailable']
                             and existing_custom != strain }}}}
                    sequence:
                      - action: persistent_notification.create
                        data:
                          title: "Build a Plant · assignment failed"
                          message: "Custom {{{{ custom_slot }}}} is '{{{{ existing_custom }}}}'. Choose another slot or clear it before assigning '{{{{ strain }}}}'."
                      - stop: "Custom slot occupied by a different strain"
                        error: true
              - action: script.dsc_custom_fill_from_catalog
                data:
                  slot: "{{{{ custom_slot }}}}"
                  seed_name: "{{{{ strain }}}}"
                continue_on_error: true
              - choose:
                  - conditions:
                      - condition: template
                        value_template: >-
                          {{{{ states('input_text.dsc_custom_strain_' ~ custom_slot ~ '_name')|trim != strain }}}}
                    sequence:
                      - action: input_text.set_value
                        target:
                          entity_id: "input_text.dsc_custom_strain_{{{{ custom_slot }}}}_name"
                        data:
                          value: "{{{{ strain }}}}"
                      - action: input_number.set_value
                        target:
                          entity_id:
                            - "input_number.dsc_custom_strain_{{{{ custom_slot }}}}_temp_min"
                            - "input_number.dsc_custom_strain_{{{{ custom_slot }}}}_temp_max"
                            - "input_number.dsc_custom_strain_{{{{ custom_slot }}}}_rh_min"
                            - "input_number.dsc_custom_strain_{{{{ custom_slot }}}}_rh_max"
                        data:
                          value: 0
      - action: input_select.select_option
        target:
          entity_id: "input_select.dsc_pot{{{{ n }}}}_strain"
        data:
          option: "{{{{ strain_option }}}}"
      - action: select.select_option
        target:
          entity_id: "select.dsc_pot{{{{ n }}}}_strain"
        data:
          option: "{{{{ strain_option }}}}"
        continue_on_error: true
      - action: select.select_option
        target:
          entity_id: "select.dsc_pot_{{{{ n }}}}_strain"
        data:
          option: "{{{{ strain_option }}}}"
        continue_on_error: true
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{{{ states('input_select.dsc_pot' ~ n ~ '_strain') != strain_option }}}}
            sequence:
              - action: persistent_notification.create
                data:
                  title: "Build a Plant · assignment failed"
                  message: "POT{{{{ n }}}} did not confirm strain option {{{{ strain_option }}}}. Check pot connectivity and entity IDs."
              - stop: "Pot strain selection was not confirmed"
                error: true
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{{{ sprout|regex_match('^\\d{{4}}-\\d{{2}}-\\d{{2}}$') }}}}
            sequence:
              - action: input_datetime.set_datetime
                target:
                  entity_id: "input_datetime.dsc_pot{{{{ n }}}}_sprout_date"
                data:
                  date: "{{{{ sprout }}}}"
              - action: date.set_value
                target:
                  entity_id: "date.dsc_pot_{{{{ n }}}}_sprout_date"
                data:
                  date: "{{{{ sprout }}}}"
                continue_on_error: true
              - action: date.set_value
                target:
                  entity_id: "date.dsc_pot{{{{ n }}}}_sprout_date"
                data:
                  date: "{{{{ sprout }}}}"
                continue_on_error: true
              - action: datetime.set_value
                target:
                  entity_id: "datetime.dsc_pot{{{{ n }}}}_sprout_date"
                data:
                  date: "{{{{ sprout }}}}"
                continue_on_error: true
              - action: datetime.set_value
                target:
                  entity_id: "datetime.dsc_pot_{{{{ n }}}}_sprout_date"
                data:
                  date: "{{{{ sprout }}}}"
                continue_on_error: true
      - choose:
          - conditions:
              - condition: template
                value_template: "{{{{ roster_slot|int(0) > 0 }}}}"
            sequence:
              - action: input_select.select_option
                target:
                  entity_id: "input_select.dsc_plant_roster_{{{{ roster_slot }}}}_pot"
                data:
                  option: "{{{{ n }}}}"
              - action: input_select.select_option
                target:
                  entity_id: "input_select.dsc_plant_roster_{{{{ roster_slot }}}}_status"
                data:
                  option: "active"
      - action: logbook.log
        data:
          name: DSC Build Plant
          message: "Assigned {{{{ nickname }}}} ({{{{ strain }}}} via {{{{ strain_option }}}}) → POT{{{{ n }}}}"
      - action: persistent_notification.create
        data:
          title: "Build a Plant · assigned"
          message: "{{{{ nickname }}}} / {{{{ strain }}}} assigned to POT{{{{ n }}}}{{{{ ' and roster slot ' ~ roster_slot if roster_slot|int(0) > 0 else '' }}}}."

  dsc_build_plant_commit_and_assign:
    alias: "DSC Build Plant · Commit and assign"
    description: "Commit the builder to roster, then assign it when a pot is selected."
    mode: single
    sequence:
      - variables:
          roster_free: >
            {{% set ns = namespace(s=0) %}}
            {{% for i in range(1,9) %}}
              {{% if ns.s == 0 and states('input_select.dsc_plant_roster_' ~ i ~ '_status') in ['empty','unknown','unavailable',''] %}}
                {{% set ns.s = i %}}
              {{% endif %}}
            {{% endfor %}}
            {{{{ ns.s }}}}
      - choose:
          - conditions:
              - condition: template
                value_template: "{{{{ roster_free|int(0) == 0 }}}}"
            sequence:
              - action: persistent_notification.create
                data:
                  title: "Build a Plant · roster full"
                  message: "Roster is full. Commit+assign did not seat a pot."
              - stop: "Roster full — assign skipped"
                error: true
      - action: script.dsc_build_plant_commit
      - condition: template
        value_template: "{{{{ states('input_select.dsc_build_assign_pot') in ['1','2','3','4'] }}}}"
      - action: script.dsc_plant_assign_to_pot
        data:
          pot: "{{{{ states('input_select.dsc_build_assign_pot') }}}}"

  dsc_blend_autofill_from_medium:
    alias: "DSC Build Plant · Autofill medium blend"
    description: "Apply the known CANNA coco composition to the blend helpers."
    mode: restart
    sequence:
      - variables:
          medium: "{{{{ states('input_text.dsc_blend_component_1_name')|trim|lower }}}}"
      - condition: template
        value_template: "{{{{ 'canna coco' in medium }}}}"
      - action: input_text.set_value
        target:
          entity_id: input_text.dsc_blend_component_1_name
        data:
          value: "coco"
      - action: input_number.set_value
        target:
          entity_id: input_number.dsc_blend_pct_1
        data:
          value: 100
      - action: input_number.set_value
        target:
          entity_id:
            - input_number.dsc_blend_pct_2
            - input_number.dsc_blend_pct_3
        data:
          value: 0

  dsc_apply_climate_want:
    alias: "DSC Apply Climate Want"
    description: >-
      Write hub climate targets from custom-slot Want temp/RH when set (≠0).
      No-op when unset. Does not invent catalog climate bands.
    mode: single
    fields:
      pot:
        name: Pot
        description: "1–4 or Fleet"
        example: "1"
        selector:
          select:
            options: ["Fleet", "1", "2", "3", "4"]
    sequence:
      - variables:
          which: "{{{{ pot if pot is defined else states('input_select.dsc_build_climate_pot') }}}}"
          n: >
            {{% if which|string in ['1','2','3','4'] %}}{{{{ which }}}}
            {{% else %}}
              {{% set ns = namespace(ids=[]) %}}
              {{% for i in [1,2,3,4] %}}
                {{% set tw = states('sensor.dsc_pot' ~ i ~ '_want_temp_min')|float(0) %}}
                {{% set rw = states('sensor.dsc_pot' ~ i ~ '_want_rh_min')|float(0) %}}
                {{% if tw > 0 or rw > 0 %}}
                  {{% set ns.ids = ns.ids + [i|string] %}}
                {{% endif %}}
              {{% endfor %}}
              {{% if ns.ids|length == 0 %}}none
              {{% elif ns.ids|length == 1 %}}{{{{ ns.ids[0] }}}}
              {{% else %}}multi:{{{{ ns.ids|join(',') }}}}
              {{% endif %}}
            {{% endif %}}
          tmin: "{{{{ states('sensor.dsc_pot' ~ n ~ '_want_temp_min')|float(0) if n in ['1','2','3','4'] else 0 }}}}"
          tmax: "{{{{ states('sensor.dsc_pot' ~ n ~ '_want_temp_max')|float(0) if n in ['1','2','3','4'] else 0 }}}}"
          rmin: "{{{{ states('sensor.dsc_pot' ~ n ~ '_want_rh_min')|float(0) if n in ['1','2','3','4'] else 0 }}}}"
          rmax: "{{{{ states('sensor.dsc_pot' ~ n ~ '_want_rh_max')|float(0) if n in ['1','2','3','4'] else 0 }}}}"
          tmid: "{{{{ ((tmin|float(0) + tmax|float(0)) / 2)|round(1) }}}}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{{{ n == 'none' or n.startswith('multi:') }}}}"
            sequence:
              - action: persistent_notification.create
                data:
                  title: "Climate Want · Fleet refused"
                  message: >-
                    {{% if n == 'none' %}}No pot has Climate Want set. Pick pot 1–4.
                    {{% else %}}Multiple pots have Want ({{{{ n[6:] }}}}). Pick an explicit tent/pot.
                    {{% endif %}}
              - stop: "Fleet Apply requires a single Want source"
                error: true
      - choose:
          - conditions:
              - condition: template
                value_template: "{{{{ tmin|float(0) > 0 and tmax|float(0) > 0 }}}}"
            sequence:
              - action: number.set_value
                target:
                  entity_id: number.dsc_hub_target_temp
                data:
                  value: "{{{{ tmid }}}}"
          - conditions:
              - condition: template
                value_template: "{{{{ true }}}}"
            sequence:
              - action: persistent_notification.create
                data:
                  title: "Climate Want · skipped temp"
                  message: "POT{{{{ n }}}} Want temp unset (0). No catalog climate invent."
      - choose:
          - conditions:
              - condition: template
                value_template: "{{{{ rmin|float(0) > 0 and rmax|float(0) > 0 }}}}"
            sequence:
              - action: number.set_value
                target:
                  entity_id: number.dsc_hub_rh_target_min
                data:
                  value: "{{{{ rmin }}}}"
              - action: number.set_value
                target:
                  entity_id: number.dsc_hub_rh_target_max
                data:
                  value: "{{{{ rmax }}}}"
          - conditions:
              - condition: template
                value_template: "{{{{ true }}}}"
            sequence:
              - action: persistent_notification.create
                data:
                  title: "Climate Want · skipped RH"
                  message: "POT{{{{ n }}}} Want RH unset (0). No catalog climate invent."
      - condition: template
        value_template: >-
          {{{{ (tmin|float(0) > 0 and tmax|float(0) > 0)
             or (rmin|float(0) > 0 and rmax|float(0) > 0) }}}}
      - action: logbook.log
        data:
          name: DSC Apply Climate Want
          message: >-
            POT{{{{ n }}}} → temp {{{{ tmid if tmin|float(0) > 0 else 'skip' }}}} °C,
            RH {{{{ rmin }}}}–{{{{ rmax }}}}%
      - action: persistent_notification.create
        data:
          title: "Climate Want applied"
          message: >-
            POT{{{{ n }}}}: target temp {{{{ tmid if tmin|float(0) > 0 else '(skipped)' }}}} °C,
            RH {{{{ rmin if rmin|float(0) > 0 else '?' }}}}–{{{{ rmax if rmax|float(0) > 0 else '?' }}}}%.
"""
    OUT.write_text(text, encoding="utf-8")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
