"""Constants for the DSC-HUB custom panel integration."""

DOMAIN = "dsc_hub"
PANEL_JS_NAME = "dsc-hub-panel.js"
PANEL_JS_URL = f"/{DOMAIN}/{PANEL_JS_NAME}"
PANEL_ELEMENT = "dsc-hub-panel"
PANEL_URL_PATH = "dsc-hub"
PANEL_REGISTERED_KEY = "dsc_hub_panel_registered"
ASSETS_URL = f"/{DOMAIN}/assets"
SURFACE_VERSION = "6.2.0"
